services:
  Agrume\Limonade\:
    resource: '../src'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'

  # Ou juste ce service :
  Agrume\Limonade\Service\LimonadeService:
    autowire: true
    autoconfigure: true
    public: false