services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # It's a good practice to define services as private by default
  # Makes HttpClientInterface available for autowiring
  Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'

  # Makes classes in src/ available to be used as services
  # This creates a service per class whose id is the fully-qualified class name

  Agrume\Limonade\:
    resource: '../src'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'

  # Ou juste ce service :
  Agrume\Limonade\Service\LimonadeService:
    autowire: true
    autoconfigure: true
    public: false